global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link

    update_frequency: 5.0
    publish_frequency: 1.0
    
    rolling_window: true
    #static_map: false

    width: 100   #25.0
    height: 100 #25.0
    resolution: 0.1

    plugins: ["obstacle_layer", "inflation_layer"]
