global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link

    update_frequency: 5.0
    publish_frequency: 1.0
    
    rolling_window: true
    #static_map: false

    width: 100   #25.0
    height: 100 #25.0
    resolution: 0.1

    use_sim_time: true
    max_obstacle_height: 3.0 #meters

    footprint: [[-0.62, -0.44], [0.62, -0.44], [0.62, 0.44], [-0.62, 0.44]]
    robot_radius: 0.1 

    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
        track_unknown_space: true
        enabled: true
        combination_method: 1
        observation_sources: "lidar_sensor_front lidar_sensor_back"

        lidar_sensor_front: 
          sensor_frame: laser_link_front
          data_type: PointCloud2
          observation_persistence: 0.0
          min_obstacle_height: 0.8
          max_obstacle_height: 1.4
          topic: /lidar_front/lslidar_point_cloud
          marking: true
          clearing: true
          obstacle_range: 10.0
          raytrace_range: 20
          inf_is_valid: true
        
        lidar_sensor_back: 
          sensor_frame: laser_link_back
          data_type: PointCloud2
          observation_persistence: 0.0
          min_obstacle_height: 0.8
          max_obstacle_height: 1.4
          topic: /lidar_back/lslidar_point_cloud
          marking: true
          clearing: true
          obstacle_range: 10.0
          raytrace_range: 20
          inf_is_valid: true

    inflation_layer:
        enabled: true
        cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
        inflation_radius:   1.0  # max. distance from an obstacle at which costs are incurred for planning paths.

local_costmap:
  ros__parameters:
    #global_frame parameter defines what coordinate frame the costmap should run in
    global_frame: map
    #robot_base_frame parameter defines the coordinate frame the costmap should reference for the base of the robot. 
    robot_base_frame: base_link
    
    #update_frequency parameter determines the frequency, in Hz, at which the costmap will run its update loop
    update_frequency: 5.0
    #publish_frequency parameter determines the rate, in Hz, at which the costmap will publish visualization information.
    publish_frequency: 3.0

    #static_map parameter determines whether or not the costmap should initialize itself based on a map served by the map_server
    #static_map: false
    #rolling_window parameter to true means that the costmap will remain centered around the robot as the robot moves through the world
    rolling_window: true
    always_send_full_costmap: true


    #The width, height,and resolution parameters set the width (meters), height (meters), and resolution (meters/cell) of the costmap
    width: 10.0
    height: 10.0

    use_sim_time: true
    max_obstacle_height: 3.0 #meters

    footprint: [[-0.62, -0.44], [0.62, -0.44], [0.62, 0.44], [-0.62, 0.44]]
    robot_radius: 0.1 

    resolution: 0.1

    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
        track_unknown_space: true
        enabled: true
        combination_method: 1
        observation_sources: "lidar_sensor_front lidar_sensor_back"

        lidar_sensor_front: 
          sensor_frame: laser_link_front
          data_type: PointCloud2
          observation_persistence: 0.0
          min_obstacle_height: 0.8
          max_obstacle_height: 1.4
          topic: /lidar_front/lslidar_point_cloud
          marking: true
          clearing: true
          obstacle_range: 10.0
          raytrace_range: 20
          inf_is_valid: true
        
        lidar_sensor_back: 
          sensor_frame: laser_link_back
          data_type: PointCloud2
          observation_persistence: 0.0
          min_obstacle_height: 0.8
          max_obstacle_height: 1.4
          topic: /lidar_back/lslidar_point_cloud
          marking: true
          clearing: true
          obstacle_range: 10.0
          raytrace_range: 20
          inf_is_valid: true

    inflation_layer:
        enabled: true
        cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
        inflation_radius:   1.0  # max. distance from an obstacle at which costs are incurred for planning paths.

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    planner_plugins: ['NavFn']
    use_sim_time: true

    NavFn:
      plugin: 'nav2_navfn_planner/NavfnPlanner'
      use_astar: true
      allow_unknown: false
      tolerance: 0.1
      use_grid: true
      cost_factor: 0.5489
      neutral_cost: 66
      lethal_cost: 253

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 5.0
    min_x_velocity_threshold: 0.0001
    min_y_velocity_threshold: 0.0001
    min_theta_velocity_threshold: 0.0001
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    plugins: ["DWAPlanner", "EBandPlanner"]

    local_costmap: "local_costmap"
    # global_costmap: ""
    # local_costmap_topic: "/costmap/costmap"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 0.0
      stateful: true

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 1.5
      yaw_goal_tolerance: 6.0
      stateful: true
      goal_angle_tolerance: 0.1

    DWAPlanner:
      plugin: "dwb_core::DWBLocalPlanner"

      # Robot configuration parameters  
      max_vel_x: 1.0
      min_vel_x: 0.0
      max_vel_y: 0.0
      min_vel_y: 0.0

      # The velocity when robot is moving in a straight line
      max_vel_trans: 1.0
      min_vel_trans:  0.0

      max_vel_theta: 3.5
      min_vel_theta: 0.5

      min_in_place_vel_theta: 0.1
      
      # the acceleration limits of the robot in m/s^2
      acc_lim_x: 2.5
      acc_lim_y: 2.5
      acc_lim_theta: 6.0
      acc_lim_trans: 2.5

      # FORWARD SIMULATION PARAMETERS
      # sim_time: The amount of time to forward-simulate trajectories in seconds
      sim_time: 1.0
      # time_granularity: the step size to take between points on a trajectory, or how frequent should the points on this trajectory should be examined
      time_granularity: 0.1

      #angular_granularity:The step size, in radians, to take between angular samples on a given trajectory
      angular_granularity: 0.1

      #vx_samples: The number of samples to use when exploring the x velocity space
      vx_samples: 10

      #vy_samples: The number of samples to use when exploring the y velocity space
      vy_samples: 10

      #vth_samples:The number of samples to use when exploring the theta velocity space
      vtheta_samples: 20

      # TRAJECTORY SCORING PARAMETERS

      # path_distance_bias: weight for how much the local planner should stay close to the global path high value will make the local planner prefer trajectories on global path
      path_distance_bias: 32.0   

      #goal_distance_bias: is the weight for how much the robot should attempt to reach the local goal, with whatever path. Experiments show that increasing this parameter enables the robot to be less attached to the global path.
      goal_distance_bias: 24.0
    
      # occdist scale is the weight for how much the robot should attempt to avoid obstacles. A high value for this parameter results in indecisive robot that stucks in place
      occdist_scale: 0.01
    
      #forward_point_distance: The distance from the center point of the robot to place an additional scoring point, in meters
      # forward_point_distance: 0.325

      #stop_time_buffer:The amount of time that the robot must stop before a collision in order for a trajectory to be considered valid in seconds
      # stop_time_buffer: 0.2

      #scaling_speed: The absolute value of the velocity at which to start scaling the robot's footprint, in m/s
      # scaling_speed: 0.25

      #max_scaling_factor: The maximum factor to scale the robot's footprint by
      # max_scaling_factor: 0.2

      #OSCILLATION PREVENTION PARAMETERS

      #oscillation_reset_dist: How far the robot must travel in meters before oscillation flags are reset
      oscillation_reset_dist: 0.05

      # Debugging
      publish_traj_pc : true
      publish_cost_grid_pc: true
      
      # how often the planning algorithm is performed (hz)
      # controller_frequency: 10.0 

behavior_server:
  ros__parameters:
    behavior_plugins: ["clear_costmap"]
    use_sim_time: true

    clear_costmap:
      plugin: "nav2_behaviors::ClearCostmap"
      enabled: true