planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    planner_plugins: ['GridBased']

    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner'
      use_astar: true
      allow_unknown: false
      tolerance: 0.1
      use_grid: true
      cost_factor: 0.5489
      neutral_cost: 66
      lethal_cost: 253