costmap/costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    rolling_window: true
    width: 10
    height: 10
    resolution: 0.05

    obstacle_layer:
      observation_sources: laser
      laser:
        topic: /antobot_ant/scan/front
        data_type: LaserScan
        sensor_frame: laser_link_front_frame
        marking: true
        clearing: true



