costmap/costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    rolling_window: true
    width: 10
    height: 10
    resolution: 0.05
    plugins: ["obstacle_layer"]
    max_obstacle_height: 10.0
    min_obstacle_height: 0.0
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      max_obstacle_height: 10.0
      combination_method: 1
      observation_sources: laser
      laser:
        topic: /antobot_ant/scan/front
        data_type: LaserScan
        sensor_frame: laser_link_front_frame
        marking: true
        clearing: true
        max_obstacle_height: 10.0
        min_obstacle_height: 0.0



