costmap/costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: base_link
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 2.0
    rolling_window: true
    width: 10
    height: 10
    resolution: 0.05
    plugins: ["obstacle_layer"]
    always_send_full_costmap: true
  
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      max_obstacle_height: 10.0
      combination_method: 1
      track_unknown_space: false
      enabled: true

      # observation_sources: laser #tested
      # laser:
      #   topic: /antobot_ant/scan/front
      #   data_type: LaserScan
      #   sensor_frame: laser_link_front_frame
      #   marking: true
      #   clearing: true
      #   max_obstacle_height: 10.0
      #   min_obstacle_height: 0.0
      #   obstacle_max_range: 10.0
      #   obstacle_min_range: 0.0
      #   raytrace_max_range: 12.0
      #   raytrace_min_range: 0.0
      #   inf_is_valid: true
      #   observation_persistence: 0.0  # seconds

      observation_sources: lidar_front
      lidar_front:
        topic: /antobot_ant/scan/front/points
        data_type: PointCloud2
        sensor_frame: laser_link_front_frame
        marking: true
        clearing: true
        max_obstacle_height: 10.0
        min_obstacle_height: 0.0
        obstacle_max_range: 10.0
        obstacle_min_range: 0.0
        raytrace_max_range: 12.0
        raytrace_min_range: 0.0
        observation_persistence: 0.0  # seconds



