local_costmap:
  ros__parameters:
    yaml_filename: "/home/soyoung/ac_whole_ws/src/antUV/acPlatform/acRobot/antobot_nav2_costmap/config/local_costmap.yaml"

# Disable global costmap
global_costmap:
  ros__parameters:
    yaml_filename: ""

# Disable planners
planner_server:
  ros__parameters:
    expected_planner_frequency: 0.0

# Disable controllers (except for costmap initialization)
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 10.0

    # Must not be empty
    controller_plugins: ["DummyController"]

    DummyController:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ["RotateToGoal", "Oscillation"]  # must define at least one critic
      debug_trajectory_details: false

    # Required parameters, even if unused
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true





# Disable BT navigator
bt_navigator:
  ros__parameters:
    default_nav_to_pose_bt_xml: ""
